### PR TITLE
chore: make necessary changes to run on c2 image.

### PR DESCRIPTION
**Pull request by sayakpaul**
Locust tests were run on a `c2-standard-8` machine. Here are the files:

[reports-c2-8vCPU+32GB+inter_op4.tar.gz](https://github.com/sayakpaul/deploy-hf-tf-vision-models/files/9209164/reports-c2-8vCPU%2B32GB%2Binter_op4.tar.gz)

### CODE REVIEW

**Review by deep-diver — APPROVED** [review]

**Comment by sayakpaul** [comment]
@deep-diver should we maintain separate branch for the experiments for the readers so that they can easily follow along?

**Comment by sayakpaul** [comment]
> @deep-diver should we maintain separate branch for the experiments for the readers so that they can easily follow along?

@deep-diver 👀

**Comment by deep-diver** [comment]
@sayakpaul 

maybe just keep all the experiment `yamls` in `.kube/experiments` is enough?

**Comment by sayakpaul** [comment]
Makes sense. Then let me merge. I will drop another PR once I finish the experiment. Would you mind taking up the experiment on `n1-standard-8`?

**Comment by deep-diver** [comment]
@sayakpaul sure!

**Pull request merged**
